2016-01-13 12:25:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 12:37:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 13:18:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT * FROM ACCO AUTH ROLE[*]"
Syntax error in SQL statement "SELECT * FROM ACCO AUTH ROLE[*]"; SQL statement:
SELECT * FROM ACCO AUTH ROLE [42000-190]
2016-01-13 13:18:57 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Onekone/IdeaProjects/Padlock/aaa.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Onekone/IdeaProjects/Padlock/aaa.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:299)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:261)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1385)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at groupPadlock.App.go(App.java:178)
	at groupPadlock.App.main(App.java:170)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Onekone/IdeaProjects/Padlock/aaa.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Onekone/IdeaProjects/Padlock/aaa.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Onekone/IdeaProjects/Padlock/aaa.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 23 more
2016-01-13 13:19:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 13:23:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 13:56:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 13:57:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 14:52:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Набор записей не является прокручиваемым. Возможно необходимо использовать conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3249)
	at org.h2.jdbc.JdbcResultSet.first(JdbcResultSet.java:2780)
	at groupPadlock.App.padlockAuth(App.java:109)
	at groupPadlock.App.go(App.java:297)
	at groupPadlock.App.main(App.java:176)
2016-01-13 14:52:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Набор записей не является прокручиваемым. Возможно необходимо использовать conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3249)
	at org.h2.jdbc.JdbcResultSet.first(JdbcResultSet.java:2780)
	at groupPadlock.App.padlockAuth(App.java:109)
	at groupPadlock.App.go(App.java:297)
	at groupPadlock.App.main(App.java:176)
2016-01-13 14:52:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Набор записей не является прокручиваемым. Возможно необходимо использовать conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..).
The result set is not scrollable and can not be reset. You may need to use conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ..). [90128-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcResultSet.resetResult(JdbcResultSet.java:3249)
	at org.h2.jdbc.JdbcResultSet.first(JdbcResultSet.java:2780)
	at groupPadlock.App.padlockAuth(App.java:109)
	at groupPadlock.App.go(App.java:297)
	at groupPadlock.App.main(App.java:176)
2016-01-13 15:02:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "id" не найден
Column "id" not found [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3129)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3217)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:339)
	at groupPadlock.App.padlockAccess(App.java:147)
	at groupPadlock.App.go(App.java:317)
	at groupPadlock.App.main(App.java:181)
2016-01-13 15:09:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 15:11:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Параметр "#5" не установлен
Parameter "#5" is not set; SQL statement:
INSERT INTO acco VALUES ( accoId.NEXTVAL , ?   , ? , ? , ? , ?); [90012-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.Parameter.checkSet(Parameter.java:81)
	at org.h2.command.Prepared.checkParameters(Prepared.java:164)
	at org.h2.command.CommandContainer.update(CommandContainer.java:77)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
	at groupPadlock.App.go(App.java:373)
	at groupPadlock.App.main(App.java:183)
2016-01-13 15:12:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 15:17:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 15:28:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 16:56:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 17:00:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 17:12:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
2016-01-13 17:25:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-190]
